### PR TITLE
Move Ɒ, ɒ from L to XL

### PR DESCRIPTION
**Pull request by moyogo**
Ɒ is used in some non standard Americanist IPA notations, for example in Smalley 1968 (reedited in 1989) used in the Unicode proposal [L2/07-334r2.](https://www.unicode.org/L2/L2007/07334r2-strident-shona-alpha.pdf) ɒ is used in IPA. Neither is used in orthographies.

### CODE REVIEW

**Comment by moyogo** [comment]
Actually the same goes for the following:
- Ɐ, ɐ used in 18th century Edward Lhuyd’s or William Pryce’s orthography of Cornish; modern orthographies of Cornish do not use the letter.
- Ꞙ, ꞙ used in early 1900s orthography or Kimochi or in 1930s orthography of Ewe before it was replaced by Ƒ, ƒ within a couple of years; modern orthographies of those languages do not use the letter.
- ȸ, ȹ are phonetic symbols (non IPA), they have not been used in orthographies.
- ƪ, ʧ are phonetic symbols (whithdrawn IPA symbol), they haven’t been used in orthographies.
- ɡ, ɧ, ɸ, ɾ are IPA phonetic symbols, they hasn’t been used in orthographies.
- Ɡ is the uppercase of ɡ, besides an attempt at having IPA with uppercase it hasn’t been used.

They aren’t used in transliteration systems either.

**Comment by koeberlin** [comment]
Thank you, Denis! As always, your input is valuable and enlightening.
I included ɧ because I found it in a text my wife had to set for a brochure for Sierra Leone. One by another, we eliminated the notdefs, only to find characters that surely aren’t included in orthographies – but in actual texts! (like Ↄ [ROMAN NUMERAL REVERSED ONE HUNDRED] instead of Ɔ [LATIN CAPITAL LETTER OPEN O])

**Comment by moyogo** [comment]
Sorry if I’m being over skeptical but this sounds like saying ɑ U+0251 LATIN SMALL LETTER ALPHA and ɡ U+0261 LATIN SMALL LETTER SCRIPT G are used in English because their shapes are used in actual texts and they are not a U+0061 and g U+0067.

Open o has variant forms, both turned-c and reversed-c, several languages have either depending on what document is looked at.
For example the printed Ifè Bible translation used the reversed-c form and LATIN SMALL LETTER REVERSED C ended up in the digital version, but Ifè orthography references consistently use LATIN SMALL LETTER OPEN O.

I’d be curious to see the texts where all these come from.

**Comment by koeberlin** [comment]
> I’d be curious to see the texts where all these come from.

I’ll send you the PDF!

**Comment by koeberlin** [comment]
Hi @moyogo, sorry, I forgot to include your changes in v1.0.0 …
In v1.0.1 I followed most of your suggestions. I only kept **ɾ Ɐ ɐ Ɡ ɡ** because I found them in other encodings such as Glyphs’ Pan-African, Questrial font, and OmniLatin.
Thank you again!

**Comment by moyogo** [comment]
Ok. Since then, Ɐ ɐ is attested in one orthography of Koalib used by a couple of authors.

ɾ is phonetic only, I'd strongly recommend keeping it only in phonetic sets. The big red flag is that it has no uppercase and nobody has shown evidence of actual use in orthography. I think Glyphs.app African set had it and the error propagated from there.

ɡ is phonetic only as well, its uppercase Ɡ is only used in documents created by Everson who proposed the character for mixed case IPA. As far as I know OmniLatin includes it because of the g in Quinault documents using a font with a single-storey g. That is very problematic, single-storey g or a are widely used, not as separate letters but as glyph variants of g or a.

**Comment by koeberlin** [comment]
This all makes perfect sense, thank you.
Nonetheless I want to make sure that Latin L contains everything that similar approaches have.
Ɡ ɡ can be found in [OmniLatin](https://www.sharptype.co/case-studies/omni-latin-research),
ɾ can be found in Questrial and Glyphs’ own Pan-African Latin template.

**Comment by moyogo** [comment]
> ɾ can be found in Questrial and Glyphs’ own Pan-African Latin template.

For what it’s worth, had I known it would create this negative feedback loop, I would have removed it from Questrial. We left ɾ in from the Glyphs.app Pan-African because it had already been designed.

**Comment by koeberlin** [comment]
I don’t find it that negative, neither the feedback loop nor designing one more glyph that might not be needed ¯\_(ツ)_/¯

**Comment by moyogo** [comment]
Don’t get me wrong, I’m all for people designing more glyphs. I’d have a single Latin set with all the Latin glyphs if I could. But if you’re making a Pan African set with additional American indigenous languages support, then it should be that.

**Pull request merged**
